//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            this.ComputerAccessory = new HashSet<ComputerAccessory>();
            this.LinePropertyAccessory = new HashSet<LinePropertyAccessory>();
            this.NumberAccessoryProperty = new HashSet<NumberAccessoryProperty>();
            this.Photo = new HashSet<Photo>();
            this.TypeAccessoryProperty = new HashSet<TypeAccessoryProperty>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int FirmID { get; set; }
        public int CategoryID { get; set; }
        public decimal Cost { get; set; }
        public int Quantity { get; set; }
        public bool Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Firm Firm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerAccessory> ComputerAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinePropertyAccessory> LinePropertyAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NumberAccessoryProperty> NumberAccessoryProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeAccessoryProperty> TypeAccessoryProperty { get; set; }
    }
}
