//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerStoreDatabaseEntities : DbContext
    {
        public ComputerStoreDatabaseEntities()
            : base("name=ComputerStoreDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessory { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<ComputerAccessory> ComputerAccessory { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<LinePropertyAccessory> LinePropertyAccessory { get; set; }
        public virtual DbSet<NumberAccessoryProperty> NumberAccessoryProperty { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<TypeAccessoryProperty> TypeAccessoryProperty { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
    }
}
